//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFCovidItalyAnalizer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WPFCovidItalyAnalizer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Date.
        /// </summary>
        public static string AllDate {
            get {
                return ResourceManager.GetString("AllDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        public static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Hospitalized.
        /// </summary>
        public static string AverageHospital {
            get {
                return ResourceManager.GetString("AverageHospital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to between date.
        /// </summary>
        public static string BetweenDate {
            get {
                return ResourceManager.GetString("BetweenDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case per 100.000 inhabitants.
        /// </summary>
        public static string CasePerinhabitants {
            get {
                return ResourceManager.GetString("CasePerinhabitants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cases.
        /// </summary>
        public static string Cases {
            get {
                return ResourceManager.GetString("Cases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart.
        /// </summary>
        public static string Chart {
            get {
                return ResourceManager.GetString("Chart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counties.
        /// </summary>
        public static string Counties {
            get {
                return ResourceManager.GetString("Counties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to County.
        /// </summary>
        public static string County {
            get {
                return ResourceManager.GetString("County", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Cases.
        /// </summary>
        public static string CurrentCases {
            get {
                return ResourceManager.GetString("CurrentCases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily cases.
        /// </summary>
        public static string DailyCases {
            get {
                return ResourceManager.GetString("DailyCases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily cases and swabs.
        /// </summary>
        public static string DailyCasesSwabs {
            get {
                return ResourceManager.GetString("DailyCasesSwabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily deads.
        /// </summary>
        public static string DailyDeads {
            get {
                return ResourceManager.GetString("DailyDeads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily swabs.
        /// </summary>
        public static string DailySwabs {
            get {
                return ResourceManager.GetString("DailySwabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deads.
        /// </summary>
        public static string Deads {
            get {
                return ResourceManager.GetString("Deads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total deads ad range data.
        /// </summary>
        public static string DeadsInRange {
            get {
                return ResourceManager.GetString("DeadsInRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deads per 100.000 inhabitants.
        /// </summary>
        public static string DeadsPerinhabitants {
            get {
                return ResourceManager.GetString("DeadsPerinhabitants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data downloaded.
        /// </summary>
        public static string DownloadedData {
            get {
                return ResourceManager.GetString("DownloadedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting data.
        /// </summary>
        public static string DownloadingData {
            get {
                return ResourceManager.GetString("DownloadingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention: There is a conflict.
        /// </summary>
        public static string GitConflict {
            get {
                return ResourceManager.GetString("GitConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tha data is now updated.
        /// </summary>
        public static string GitFastForward {
            get {
                return ResourceManager.GetString("GitFastForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data is already up to date.
        /// </summary>
        public static string GitUpToDate {
            get {
                return ResourceManager.GetString("GitUpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home isolation.
        /// </summary>
        public static string HomeIsolation {
            get {
                return ResourceManager.GetString("HomeIsolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total hospitalized.
        /// </summary>
        public static string Hospital {
            get {
                return ResourceManager.GetString("Hospital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hospitalized.
        /// </summary>
        public static string HospitalizedWithSymptoms {
            get {
                return ResourceManager.GetString("HospitalizedWithSymptoms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intensive Care.
        /// </summary>
        public static string IntensiveCare {
            get {
                return ResourceManager.GetString("IntensiveCare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italy.
        /// </summary>
        public static string Italy {
            get {
                return ResourceManager.GetString("Italy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 7 Days.
        /// </summary>
        public static string LastSevenDays {
            get {
                return ResourceManager.GetString("LastSevenDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 6 Months.
        /// </summary>
        public static string LastSixMonths {
            get {
                return ResourceManager.GetString("LastSixMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 30 Days.
        /// </summary>
        public static string LastThirtyDays {
            get {
                return ResourceManager.GetString("LastThirtyDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 3 Months.
        /// </summary>
        public static string LastThreeMonths {
            get {
                return ResourceManager.GetString("LastThreeMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 2 Months.
        /// </summary>
        public static string LastTwoMonths {
            get {
                return ResourceManager.GetString("LastTwoMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 2 Weeks.
        /// </summary>
        public static string LastTwoWeeks {
            get {
                return ResourceManager.GetString("LastTwoWeeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Week.
        /// </summary>
        public static string LastWeek {
            get {
                return ResourceManager.GetString("LastWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Year.
        /// </summary>
        public static string LastYear {
            get {
                return ResourceManager.GetString("LastYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New cases.
        /// </summary>
        public static string NewCases {
            get {
                return ResourceManager.GetString("NewCases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total new cases at range data.
        /// </summary>
        public static string NewCasesInRange {
            get {
                return ResourceManager.GetString("NewCasesInRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] PopolazioneProvince {
            get {
                object obj = ResourceManager.GetObject("PopolazioneProvince", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] PopolazioneRegioni {
            get {
                object obj = ResourceManager.GetObject("PopolazioneRegioni", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string Region {
            get {
                return ResourceManager.GetString("Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regions.
        /// </summary>
        public static string Regions {
            get {
                return ResourceManager.GetString("Regions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationship cases and swab.
        /// </summary>
        public static string RelationshipCasesSwabs {
            get {
                return ResourceManager.GetString("RelationshipCasesSwabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Range.
        /// </summary>
        public static string SelectRange {
            get {
                return ResourceManager.GetString("SelectRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swabs.
        /// </summary>
        public static string Swabs {
            get {
                return ResourceManager.GetString("Swabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total swabs ad range data.
        /// </summary>
        public static string SwabsInRange {
            get {
                return ResourceManager.GetString("SwabsInRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swabs per 100.000 inhabitants.
        /// </summary>
        public static string SwabsPerinhabitants {
            get {
                return ResourceManager.GetString("SwabsPerinhabitants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Month.
        /// </summary>
        public static string ThisMonth {
            get {
                return ResourceManager.GetString("ThisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Week.
        /// </summary>
        public static string ThisWeek {
            get {
                return ResourceManager.GetString("ThisWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top.
        /// </summary>
        public static string Top {
            get {
                return ResourceManager.GetString("Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total cases.
        /// </summary>
        public static string TotalCases {
            get {
                return ResourceManager.GetString("TotalCases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly cases.
        /// </summary>
        public static string WeeklyCases {
            get {
                return ResourceManager.GetString("WeeklyCases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total weekly cases and average hospitalized.
        /// </summary>
        public static string WeeklyCasesHospital {
            get {
                return ResourceManager.GetString("WeeklyCasesHospital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly Cases for 100.000 Inabitant.
        /// </summary>
        public static string WeeklyCasesInhabitant {
            get {
                return ResourceManager.GetString("WeeklyCasesInhabitant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total weekly cases and swabs.
        /// </summary>
        public static string WeeklyCasesSwabs {
            get {
                return ResourceManager.GetString("WeeklyCasesSwabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total weekly deads.
        /// </summary>
        public static string WeeklyDeads {
            get {
                return ResourceManager.GetString("WeeklyDeads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total weekly swabs.
        /// </summary>
        public static string WeeklySwabs {
            get {
                return ResourceManager.GetString("WeeklySwabs", resourceCulture);
            }
        }
    }
}
